
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace lubanTable.demo
{
public sealed partial class RewardPack : Luban.BeanBase
{
    public RewardPack(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["skey"].IsString) { throw new SerializationException(); }  Skey = _buf["skey"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["reawrds"]; if(!__json0.IsArray) { throw new SerializationException(); } Reawrds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Reawrds.Add(__v0); }   }
    }

    public static RewardPack DeserializeRewardPack(JSONNode _buf)
    {
        return new demo.RewardPack(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 策划使用的名称
    /// </summary>
    public readonly string Skey;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 奖励列表，从奖励表中获取
    /// </summary>
    public readonly System.Collections.Generic.List<string> Reawrds;
   
    public const int __ID__ = -1229162765;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skey:" + Skey + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "reawrds:" + Luban.StringUtil.CollectionToString(Reawrds) + ","
        + "}";
    }
}
}

