
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace lubanTable.demo
{
public partial class TbRewardPack
{
    private readonly System.Collections.Generic.Dictionary<int, demo.RewardPack> _dataMap;
    private readonly System.Collections.Generic.List<demo.RewardPack> _dataList;
    
    public TbRewardPack(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.RewardPack>();
        _dataList = new System.Collections.Generic.List<demo.RewardPack>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.RewardPack _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::lubanTable.demo.RewardPack.DeserializeRewardPack(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.RewardPack> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.RewardPack> DataList => _dataList;

    public demo.RewardPack GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.RewardPack Get(int key) => _dataMap[key];
    public demo.RewardPack this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

