
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace lubanTable.demo
{
public partial class TbReward
{
    private readonly System.Collections.Generic.List<demo.Reward> _dataList;

    private System.Collections.Generic.Dictionary<int, demo.Reward> _dataMap_id;
    private System.Collections.Generic.Dictionary<string, demo.Reward> _dataMap_skey;

    public TbReward(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<demo.Reward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Reward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::lubanTable.demo.Reward.DeserializeReward(_ele);  }
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, demo.Reward>();
        _dataMap_skey = new System.Collections.Generic.Dictionary<string, demo.Reward>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_skey.Add(_v.Skey, _v);
    }
    }

    public System.Collections.Generic.List<demo.Reward> DataList => _dataList;

    public demo.Reward GetById(int key) => _dataMap_id.TryGetValue(key, out demo.Reward __v) ? __v : null;
    public demo.Reward GetBySkey(string key) => _dataMap_skey.TryGetValue(key, out demo.Reward __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

